apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-config
  namespace: default
  labels:
    app: messaging-app
data:
  DJANGO_SETTINGS_MODULE: "messaging_app.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
